---
name: 'Goose AI Action'
description: 'Sets up Goose AI using pipx'
inputs:
  profile:
    description: 'Profile configuration for goose-ai'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Run Goose AI'
      shell: bash
      run: |
        cp .github/actions/goose-action/profiles.yaml /root/.goose/config/profiles.yaml
        cp .github/actions/goose-action/plan.yaml /root/.goose/config/plan.yaml
        /entrypoint.sh
env:
  PLAN: $(cat .github/actions/goose-action/plan.yaml)
