---
name: "Goose AI Action"
description: "Sets up Goose AI with pipx"
inputs:
  profile:
    description: 'Profile configuration for Goose AI'
    required: true
  task_request:
    description: 'Task request for Goose AI to complete'
    required: true


runs:
  using: "docker"
  image: "Dockerfile"
