kickoff_message: |
    This will follow tasks as given for the project and then try to complete them without input. 
    exit when finished or attempt is finished after trying.

tasks:
 - you are running in a CI style environment and aim to try to complete the task assigned
 - keep iterating as best you can to completion until the task is satisfied, and tests are run.
 - Task -> {TASK}
 - if successful write to a file ./success, and if a failure to ./failure
