name: ci

on: [push, pull_request]
jobs:
  ask-goose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2


      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # You can specify the Ruby version you need

      - name: Verify Ruby installation
        run: ruby -v
