name: Validate Goose Action

on:
  pull_request:

jobs:
  validate-goose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2


      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # You can specify the Ruby version you need

      - name: Verify Ruby installation
        run: ruby -v

      - name: Run Goose Action
        uses: ./.github/actions/goose-action
        with:
          task_request: "run ruby to check the version"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
