name: Validate Goose Action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-goose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'


      - name: Run Goose Action
        uses: ./.github/actions/goose-action
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}